version: "3.9"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017"
    networks:
      - ml
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo

  mongo-seed:
    image: mongo:latest
    volumes:
      - ./data:/data-import
    networks:
      - ml
    depends_on:
      - mongodb
    command: bash -c "
      mongoimport -h mongodb -u mongo -p mongo --authenticationDatabase admin -d samples -c tmdb_movies --type csv --headerline --drop /data-import/movies/tmdb_movies_data.csv
      && mongoimport -h mongodb -u mongo -p mongo --authenticationDatabase admin -d samples -c movies --type csv --headerline --drop /data-import/movies/movies.csv
      && mongoimport -h mongodb -u mongo -p mongo --authenticationDatabase admin -d samples -c ratings --type csv --headerline --drop /data-import/movies/ratings.csv"

  redis:
    image: redis:latest
    ports:
      - "6379"
    networks:
      - ml

  ai-service:
    image: ghcr.io/xii1/movie-recommender:$AI_SERVICE_TAG
    volumes:
      - trained_models:/app/trained_models
    ports:
      - "8080"
    restart: always
    networks:
      - ml
    depends_on:
      - mongodb
      - redis

  load-balancer:
    image: nginx:latest
    volumes:
      - ./deploy/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - ml
    depends_on:
      - ai-service

networks:
  ml:
volumes:
  trained_models: